// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM0JNR0cL8Oyqb3R8OnnF8FLWLrz0QOCI',
    appId: '1:234853165577:web:ef365dd72ce07223b5e6d8',
    messagingSenderId: '234853165577',
    projectId: 'gerenciador-tarefas-a2b1d',
    authDomain: 'gerenciador-tarefas-a2b1d.firebaseapp.com',
    storageBucket: 'gerenciador-tarefas-a2b1d.firebasestorage.app',
    measurementId: 'G-LT8MGHHZHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnbvM7gy_9m_OgnuO3OoG1axyKXVrZQ5o',
    appId: '1:234853165577:android:c5de4f1d0d50be69b5e6d8',
    messagingSenderId: '234853165577',
    projectId: 'gerenciador-tarefas-a2b1d',
    storageBucket: 'gerenciador-tarefas-a2b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrSA9u8IBlc_yxPJVENgzUYoQdLCPP3So',
    appId: '1:234853165577:ios:be992db6ad61965bb5e6d8',
    messagingSenderId: '234853165577',
    projectId: 'gerenciador-tarefas-a2b1d',
    storageBucket: 'gerenciador-tarefas-a2b1d.firebasestorage.app',
    iosClientId: '234853165577-cnvmfi0kgs48as4v1nuic1vmm9llbi5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.gerenciadorTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrSA9u8IBlc_yxPJVENgzUYoQdLCPP3So',
    appId: '1:234853165577:ios:be992db6ad61965bb5e6d8',
    messagingSenderId: '234853165577',
    projectId: 'gerenciador-tarefas-a2b1d',
    storageBucket: 'gerenciador-tarefas-a2b1d.firebasestorage.app',
    iosClientId: '234853165577-cnvmfi0kgs48as4v1nuic1vmm9llbi5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.gerenciadorTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM0JNR0cL8Oyqb3R8OnnF8FLWLrz0QOCI',
    appId: '1:234853165577:web:c875038bfc8c4301b5e6d8',
    messagingSenderId: '234853165577',
    projectId: 'gerenciador-tarefas-a2b1d',
    authDomain: 'gerenciador-tarefas-a2b1d.firebaseapp.com',
    storageBucket: 'gerenciador-tarefas-a2b1d.firebasestorage.app',
    measurementId: 'G-LZGL9V9WL4',
  );

}